//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSTowers
{
    using System;
    using System.Collections.Generic;
    
    public partial class estado
    {
        public estado()
        {
            this.cidade = new HashSet<cidade>();
        }
    
        public int id { get; set; }
        public string Estado1 { get; set; }
        public string Sigla { get; set; }
        public Nullable<int> Regiao { get; set; }
    
        public virtual ICollection<cidade> cidade { get; set; }
        public virtual regiao regiao1 { get; set; }
    }
}
