//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSTowers
{
    using System;
    using System.Collections.Generic;
    
    public partial class loja
    {
        public loja()
        {
            this.estoque = new HashSet<estoque>();
            this.vendas = new HashSet<vendas>();
        }
    
        public int id { get; set; }
        public string loja1 { get; set; }
    
        public virtual ICollection<estoque> estoque { get; set; }
        public virtual ICollection<vendas> vendas { get; set; }
    }
}
