//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSTowers
{
    using System;
    using System.Collections.Generic;
    
    public partial class participante
    {
        public participante()
        {
            this.vendas = new HashSet<vendas>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public Nullable<int> idade { get; set; }
        public Nullable<int> cidade { get; set; }
        public Nullable<int> genero { get; set; }
    
        public virtual cidade cidade1 { get; set; }
        public virtual genero genero1 { get; set; }
        public virtual ICollection<vendas> vendas { get; set; }
    }
}
