//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSTowers
{
    using System;
    using System.Collections.Generic;
    
    public partial class regiao
    {
        public regiao()
        {
            this.estado = new HashSet<estado>();
        }
    
        public int id { get; set; }
        public string Regiao1 { get; set; }
    
        public virtual ICollection<estado> estado { get; set; }
    }
}
